const blogs = [
  {
    _id: 1,
    title: "5 Ways to Optimize Instagram SEO, Increase Your Account Visibility",
    path: "optimize-instagram-seo",
    date: "September 10, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680151015/Blog%20MSN/01-5_Cara_Optimasi_SEO_Instagram_Tingkatkan_Visibilitas_Akun_Mu_e0acku.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["instagram", "seo", "optimization", "technology"],
    description: "Instagram is one of the largest social media platforms in the world. With over one billion active users every month, Instagram provides great opportunities for businesses and individuals to promote their brand and reach a wider audience. However, to fully leverage Instagram's potential, you need to ensure that your account is optimized for SEO. Below are five ways to optimize your Instagram SEO and increase your account visibility...",
  },
  {
    _id: 2,
    title: "5 Career Prospects for Information Technology Graduates",
    path: "it-career-prospects",
    date: "September 20, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680154547/Blog%20MSN/5_Prospek_Pekerjaan_Jurusan_Teknik_Informatika_leo1iw.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["information-technology", "it", "prospects", "informatics", "career", "technology"],
    description: "Information Technology is one of the majors with promising career prospects in the future. This is due to the rapid development of technology and the high demand for experts in the field of information technology. Here are five career prospects that can be pursued by Information Technology graduates...",
  },
  {
    _id: 3,
    title: "Understanding Redux: How It Works & Its Advantages",
    path: "understanding-redux",
    date: "September 25, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680156651/Blog%20MSN/REDUX_d0qd51.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["redux", "react-redux"],
    description: "Redux is an open-source JavaScript library used to manage state or data in complex web applications. Redux is designed to be used with React, but can also be used with other JavaScript frameworks such as Angular or Vue. Redux helps developers build highly scalable, easy to maintain, and easy to test web applications...",
  },
  {
    _id: 4,
    title: "The Promise and Potential of 5G Technology",
    path: "5g-technology",
    date: "November 06, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680158117/Blog%20MSN/teknologi-5g_w9c16l.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["5g-technology", "5g", "network", "technology"],
    description: "5G cellular technology is the latest generation of cellular network technology. 5G promises faster download and upload speeds, lower latency, and more reliable connections. In this blog, we will discuss the potential of 5G technology and the challenges that need to be addressed...",
  },
  {
    _id: 5,
    title: "5 Latest Technologies That Will Change How We Live",
    path: "latest-technologies",
    date: "November 09, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680159590/Blog%20MSN/5_Teknologi_Terbaru_yang_Akan_Mengubah_Cara_Kita_Hidup_h4qzjc.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["latest-technology", "technology", "iot", "ai", "ar", "blockchain", "quantum-computing"],
    description: "Technology continues to develop rapidly and has a big impact on our lives. There are several new technologies that will change the way we live in the future. Here are 5 latest technologies that will change how we live...",
  },
  {
    _id: 6,
    title: "How Cloud Computing Technology Helps Improve Business Efficiency",
    path: "cloud-computing",
    date: "November 12, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680161513/Blog%20MSN/Bagaimana_Teknologi_Cloud_Computing_Membantu_Meningkatkan_Efisiensi_Bisnis_r8zznr.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["cloud-computing", "business", "technology", "efficiency"],
    description: "Cloud computing technology has brought major changes in the way companies store, manage, and process their data. By storing data and applications in the cloud, companies can improve their business efficiency and speed up response times to customers. In this article, we will discuss how cloud computing technology helps improve business efficiency...",
  },
  {
    _id: 7,
    title: "Understanding AI (Artificial Intelligence) and Its Role in the World of Technology",
    path: "understanding-artificial-intelligence",
    date: "November 15, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680162572/Blog%20MSN/Mengenal_AI_Artificial_Intelligence_dan_Perannya_dalam_Dunia_Teknologi_bypsuh.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["artificial-intelligence", "ai", "technology"],
    description: "Artificial Intelligence (AI) is a technology that allows computers to perform tasks that previously could only be done by humans. AI has developed rapidly in recent years and has played an important role in various fields of technology, including computers, telecommunications, transportation, healthcare, and many more...",
  },
  {
    _id: 8,
    title: "Understanding the Metaverse and Its Impact on Life",
    path: "understanding-metaverse",
    date: "November 28, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680164600/Blog%20MSN/metaverse_gkeb3w.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["metaverse", "life-technology", "technology"],
    description: "In the increasingly developing digital era, the concept of the Metaverse is increasingly being heard. The Metaverse is a concept that describes a virtual world that merges with the real world. This term was first used by science fiction writer Neal Stephenson in his novel Snow Crash published in 1992...",
  },
  {
    _id: 9,
    title: "Why the Internet of Things (IoT) Will Be the Biggest Technology Trend in the Future",
    path: "internet-of-things",
    date: "November 30, 2022",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680165664/Blog%20MSN/iot_slasgq.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["iot", "internet-of-things", "technology-trend", "future"],
    description: "The Internet of Things (IoT) is a concept that refers to a network of physical devices connected to the internet and communicating with each other. Examples include cars, lights, refrigerators, even clothes connected to the internet. In this article, we will discuss why IoT will be the biggest technology trend in the future...",
  },
  {
    _id: 10,
    title: "Understanding Big Data Technology to Optimize Your Business",
    path: "understanding-big-data",
    date: "January 12, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680167041/Blog%20MSN/BIG-DATA_g70lqg.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["big-data", "big", "data", "business", "technology"],
    description: "Big Data technology is becoming increasingly important in today's business world. In the era of digitalization, many companies collect data from various sources, including customer data, transaction data, social media data, and other data. However, data collection alone is not enough. Companies must also be able to analyze and utilize this data to improve efficiency, productivity, and business profits...",
  },
  {
    _id: 11,
    title: "Why SMEs Need a Website",
    path: "sme-website",
    date: "January 28, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680169583/Blog%20MSN/UKM-WEBSITE_udqv0o.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["sme", "website", "small-medium-enterprise", "technology"],
    description: "SMEs or Small and Medium Enterprises are a business sector that plays an important role in a country's economy. In Indonesia, SMEs are even categorized as the backbone of the economy with the number of businesses reaching around 63 million units. Therefore, in the digital era like today, the existence of a website becomes a necessity for SMEs. Here are some reasons why SMEs need a website...",
  },
  {
    _id: 12,
    title: "Understanding the Difference Between Front End and Back End Developers",
    path: "understanding-frontend-backend-developers",
    date: "February 07, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680187840/Blog%20MSN/fronted-backend-developer_maczhk.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["frontend-developer", "backend-developer", "web-developer", "software-engineer"],
    description: "In website or application development, there are two main types of developers involved, namely front-end developers and back-end developers. Although both focus on web development, their tasks and responsibilities are very different. In this blog, we will discuss the differences between front-end developers and back-end developers...",
  },
  {
    _id: 13,
    title: "Understanding What a Proxy Server Is & How It Works",
    path: "understanding-proxy-server",
    date: "February 23, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680189684/Blog%20MSN/proxy-serevr_wzls0y.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["proxy-server", "proxy", "server"],
    description: "A proxy server or often referred to as a proxy is a server that functions as an intermediary between the user's computer and the internet. By using a proxy server, internet users can hide their original IP address and provide safer and more controlled access to the internet. Proxy servers can be used to speed up internet access, save bandwidth, block access to certain sites, and much more...",
  },
  {
    _id: 14,
    title: "Understanding Ecommerce Marketing Strategies For Your Business",
    path: "understanding-ecommerce-marketing-strategies",
    date: "March 09, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680192645/Blog%20MSN/ecommerce-marketing_omm6ep.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["e-commerce", "marketing", "strategy", "business"],
    description: "If you run an ecommerce business, then you need to understand that it's important to have an effective marketing strategy to promote your products, attract new customers, and increase sales. In this blog, we will discuss several ecommerce marketing strategies that you can use to grow your business...",
  },
  {
    _id: 15,
    title: "Understanding What CMS Is, Its Benefits & How It Works",
    path: "understanding-cms",
    date: "March 21, 2023",
    // img: "https://res.cloudinary.com/dh6s3dche/image/upload/v1680191358/Blog%20MSN/cms_qmdhgp.jpg",
    instagram_link: "https://www.instagram.com/msn.production/",
    linkedin_link: "https://www.linkedin.com/in/mulia-sejati-nusantara-production-a766b3258/",
    tags: ["cms", "wordpress", "joomla", "drupal", "magento"],
    description: "CMS or Content Management System is a content management system that allows users to create, edit, and manage content on a website without needing deep technical knowledge. CMS is typically used to manage websites, blogs, forums, or even online stores...",
  },
];

export default blogs;
